### ISSUE TITLE
Installation impossible on Heroku 

### ISSUE THREAD

**Issue by CYB3RL1F3** [cryptocoinjs/scrypt#3]
Hello, 
I can't setup my app on heroku, I meet the following error: 

```
2020-04-15T00:13:13.350616+00:00 app[web.1]: yarn run v1.22.4
2020-04-15T00:13:13.448944+00:00 app[web.1]: $ yarn install && tsc
2020-04-15T00:13:14.411964+00:00 app[web.1]: [1/5] Validating package.json...
2020-04-15T00:13:14.421427+00:00 app[web.1]: [2/5] Resolving packages...
2020-04-15T00:13:15.121644+00:00 app[web.1]: [3/5] Fetching packages...
2020-04-15T00:13:25.808347+00:00 heroku[web.1]: State changed from crashed to starting
2020-04-15T00:13:30.367846+00:00 app[web.1]: warning " > babel-watch@7.0.0" has unmet peer dependency "@babel/core@^7.0.0".
2020-04-15T00:13:37.536373+00:00 app[web.1]: [5/5] Building fresh packages...
2020-04-15T00:13:40.957705+00:00 heroku[web.1]: State changed from starting to crashed
2020-04-15T00:13:40.825467+00:00 app[web.1]: error /app/node_modules/scrypt: Command failed.
2020-04-15T00:13:40.825480+00:00 app[web.1]: Exit code: 1
2020-04-15T00:13:40.825481+00:00 app[web.1]: Command: node-gyp rebuild
2020-04-15T00:13:40.825481+00:00 app[web.1]: Arguments: 
2020-04-15T00:13:40.825482+00:00 app[web.1]: Directory: /app/node_modules/scrypt
2020-04-15T00:13:40.825482+00:00 app[web.1]: Output:
2020-04-15T00:13:40.825483+00:00 app[web.1]: make: Entering directory '/app/node_modules/scrypt/build'
2020-04-15T00:13:40.825483+00:00 app[web.1]:   SOLINK_MODULE(target) Release/obj.target/copied_files.node
2020-04-15T00:13:40.825484+00:00 app[web.1]: make: g++: Command not found
2020-04-15T00:13:40.825484+00:00 app[web.1]: copied_files.target.mk:22: recipe for target 'Release/obj.target/copied_files.node' failed
2020-04-15T00:13:40.825485+00:00 app[web.1]: make: *** [Release/obj.target/copied_files.node] Error 127
2020-04-15T00:13:40.825486+00:00 app[web.1]: make: Leaving directory '/app/node_modules/scrypt/build'
2020-04-15T00:13:40.825486+00:00 app[web.1]: gyp ERR! build error 
2020-04-15T00:13:40.825487+00:00 app[web.1]: gyp ERR! stack Error: `make` failed with exit code: 2
2020-04-15T00:13:40.825487+00:00 app[web.1]: gyp ERR! stack     at ChildProcess.onExit (/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
2020-04-15T00:13:40.825488+00:00 app[web.1]: gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
2020-04-15T00:13:40.825488+00:00 app[web.1]: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
2020-04-15T00:13:40.825488+00:00 app[web.1]: gyp ERR! System Linux 4.4.0-1062-aws
2020-04-15T00:13:40.825491+00:00 app[web.1]: gyp ERR! command "/app/.heroku/node/bin/node" "/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-04-15T00:13:40.825491+00:00 app[web.1]: gyp ERR! cwd /app/node_modules/scrypt
2020-04-15T00:13:40.825491+00:00 app[web.1]: gyp ERR! node -v v10.6.0
2020-04-15T00:13:40.825492+00:00 app[web.1]: gyp ERR! node-gyp -v v3.8.0
2020-04-15T00:13:40.825492+00:00 app[web.1]: gyp ERR! not ok
2020-04-15T00:13:40.825515+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2020-04-15T00:13:40.869252+00:00 app[web.1]: error Command failed with exit code 1.
2020-04-15T00:13:40.869397+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2020-04-15T00:13:40.888363+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-04-15T00:13:40.888736+00:00 app[web.1]: npm ERR! errno 1
2020-04-15T00:13:40.889831+00:00 app[web.1]: npm ERR! profilart@1.1.0 start: `yarn run build && node ./dist/index.js`
2020-04-15T00:13:40.889974+00:00 app[web.1]: npm ERR! Exit status 1
2020-04-15T00:13:40.890175+00:00 app[web.1]: npm ERR! 
2020-04-15T00:13:40.890299+00:00 app[web.1]: npm ERR! Failed at the profilart@1.1.0 start script.
2020-04-15T00:13:40.890404+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-04-15T00:13:40.897369+00:00 app[web.1]: 
2020-04-15T00:13:40.897487+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
```

A clue? I'm desperated... I tried all kind of versions possible, I don't know if the problem is from heroku or here. It works perfectly locally with node 10.6.0, but not on heroku, despite the engine precision made on package.json.

Thanks for the help!

**Comment by junderw** [comment]
The error says "g++: Command not found"

Heroku Dyno doesn't have g++ so native source can't be compiled.

https://stackoverflow.com/questions/44060917/heroku-how-do-i-install-run-g-on-a-dyno

This issue says to look into using docker containers.
